[package]
name = "learning-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
prettytable-rs = "0.10"
toml = "0.5.9"
serde = { version = "1.0.147", features = ["derive"] }
